#!/bin/sh

# TechOGR: a GTK3 theme generated from the active palette (Adwaita dark +
# the neon look of RiceEditor). Rebuilt on every theme apply, so Thunar and
# every other GTK3 app follow palette changes. It's the default gtk_theme;
# any other installed theme can still be picked in RiceEditor -> GTK.
_gtk_dir="$HOME/.local/share/themes/TechOGR/gtk-3.0"
mkdir -p "$_gtk_dir"
printf '[Desktop Entry]\nType=X-GNOME-Metatheme\nName=TechOGR\nComment=Generated from the rice palette\n\n[X-GNOME-Metatheme]\nGtkTheme=TechOGR\n' \
    >"$_gtk_dir/../index.theme"
_write "$_gtk_dir/gtk.css" <<EOF
/* Generated by config/modules/03-gtk.sh - edits are overwritten */
@import url("resource:///org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css");

@define-color bg ${bg};
@define-color fg ${fg};
@define-color black ${black};
@define-color blackb ${blackb};
@define-color accent ${blue};
@define-color accent2 ${magenta};
@define-color cyan ${cyan};
@define-color red ${red};

@define-color theme_bg_color @bg;
@define-color theme_fg_color @fg;
@define-color theme_base_color @bg;
@define-color theme_text_color @fg;
@define-color theme_selected_bg_color @accent;
@define-color theme_selected_fg_color @bg;
@define-color borders alpha(@accent, 0.18);

window, .background, dialog, messagedialog, .view, iconview, treeview, textview text,
scrolledwindow, viewport, notebook > stack {
    background-color: @bg;
    color: @fg;
}
label { color: @fg; }
.dim-label, label.dim-label { color: alpha(@fg, 0.5); }

/* menubar / toolbar / headerbar */
menubar, toolbar, headerbar, .titlebar {
    background-image: none;
    background-color: @black;
    border-bottom: 1px solid alpha(@accent, 0.18);
    box-shadow: none;
    color: @fg;
}
menubar > menuitem { color: alpha(@fg, 0.75); padding: 4px 10px; }
menubar > menuitem:hover { color: @accent; box-shadow: inset 0 -2px @accent; }

menu, .menu, .context-menu, popover, popover.background {
    background-color: @black;
    border: 1px solid alpha(@accent, 0.30);
    border-radius: 10px;
    color: @fg;
}
menu menuitem, .menu menuitem { padding: 5px 12px; border-radius: 6px; }
menu menuitem:hover, .menu menuitem:hover {
    background-color: alpha(@accent, 0.18);
    color: @accent;
}
menu menuitem:hover label, .menu menuitem:hover label, menu menuitem:hover accelerator { color: @accent; }
menu separator, .menu separator { background-color: alpha(@accent, 0.14); }

/* buttons */
button {
    background-image: none;
    background-color: alpha(@accent, 0.08);
    border: 1px solid alpha(@accent, 0.22);
    border-radius: 10px;
    box-shadow: none;
    text-shadow: none;
    color: @fg;
}
button:hover {
    background-color: alpha(@accent, 0.20);
    border-color: alpha(@accent, 0.55);
    box-shadow: 0 0 10px alpha(@accent, 0.30);
    color: @accent;
}
button:checked, button:active {
    background-color: alpha(@accent, 0.30);
    border-color: @accent;
    color: @accent;
}
button:disabled { background-color: transparent; border-color: alpha(@fg, 0.06); color: alpha(@fg, 0.3); }
toolbar button, headerbar button, .path-bar button, .linked > button { border-radius: 8px; }
toolbar button:not(:hover):not(:checked), headerbar button:not(:hover):not(:checked) {
    background-color: transparent;
    border-color: transparent;
}

/* location entry / search */
entry {
    background-image: none;
    background-color: alpha(@blackb, 0.35);
    border: 1px solid alpha(@accent, 0.22);
    border-radius: 10px;
    box-shadow: none;
    color: @fg;
    caret-color: @accent;
}
entry:focus {
    border-color: @accent;
    box-shadow: 0 0 10px alpha(@accent, 0.35);
}
entry image { color: @accent; }
entry selection, selection { background-color: alpha(@accent, 0.35); color: @fg; }

/* sidebar (Lugares / Dispositivos) */
.sidebar, placessidebar, placessidebar list, .sidebar list, .thunar .sidebar {
    background-image: linear-gradient(to bottom, alpha(@black, 0.95), @bg);
    border-right: 1px solid alpha(@accent, 0.20);
    color: alpha(@fg, 0.75);
}
.sidebar treeview.view, .sidebar .view {
    background-color: transparent;
    color: alpha(@fg, 0.75);
}
.sidebar treeview.view:hover, .sidebar .view:hover { background-color: alpha(@accent, 0.10); color: @fg; }
.sidebar treeview.view:selected, .sidebar .view:selected,
placessidebar row:selected {
    background-image: linear-gradient(to right, alpha(@accent, 0.30), alpha(@accent, 0.02));
    color: @accent;
    box-shadow: inset 3px 0 0 @accent;
}
.sidebar treeview.view header button, placessidebar .sidebar-placeholder-row { color: @accent; }
placessidebar row { border-radius: 8px; margin: 1px 6px; }
placessidebar row:hover { background-color: alpha(@accent, 0.10); }

/* file views */
.view:hover, iconview:hover { color: @fg; }
.view:selected, iconview:selected, treeview.view:selected,
.view:selected:focus, iconview:selected:focus, treeview.view:selected:focus,
.view text:selected, iconview text:selected {
    background-color: alpha(@accent, 0.28);
    color: @fg;
    border-radius: 8px;
}
iconview.view { -gtk-outline-radius: 8px; }
.view.dnd, iconview:drop(active) { border: 1px solid @accent; }
.rubberband, rubberband, .view.rubberband, iconview.rubberband {
    background-color: alpha(@accent, 0.15);
    border: 1px solid @accent;
}
treeview.view header button {
    background-color: @black;
    border: none;
    border-bottom: 1px solid alpha(@accent, 0.18);
    border-radius: 0;
    color: @accent;
    font-weight: bold;
}
treeview.view header button:hover { background-color: alpha(@accent, 0.12); box-shadow: none; }

/* statusbar */
statusbar, .statusbar {
    background-color: @black;
    border-top: 1px solid alpha(@accent, 0.18);
    color: alpha(@fg, 0.6);
}

/* scrollbars */
scrollbar, scrollbar.vertical, scrollbar.horizontal { background-color: transparent; border: none; }
scrollbar slider {
    background-color: alpha(@accent, 0.35);
    border-radius: 8px;
    min-width: 6px;
    min-height: 6px;
    border: none;
}
scrollbar slider:hover { background-color: @accent; }

/* panes, notebooks (tabs), separators */
paned > separator { background-color: alpha(@accent, 0.18); background-image: none; }
notebook > header { background-color: @black; border-color: alpha(@accent, 0.18); }
notebook > header tab { color: alpha(@fg, 0.55); }
notebook > header tab:checked { color: @accent; box-shadow: inset 0 -2px @accent; }
separator { background-color: alpha(@accent, 0.12); }

/* checks, radios, switches, progress */
check:checked, radio:checked, switch:checked {
    background-image: none;
    background-color: @accent;
    border-color: @accent;
    color: @bg;
}
progressbar progress, levelbar block.filled, scale highlight {
    background-image: linear-gradient(to right, @accent2, @accent);
    border: none;
}

tooltip, tooltip.background {
    background-color: @black;
    border: 1px solid alpha(@accent, 0.35);
    border-radius: 8px;
    color: @fg;
}
tooltip label { color: @fg; }
EOF

# Fall back when the configured themes aren't installed (the old default
# TokyoNight-zk / TokyoNight-SE were never shipped): GTK then silently
# dropped to the light default theme.
_have_theme() {
    for _d in "$HOME/.local/share/$1" "$HOME/.$1" "/usr/share/$1"; do
        [ -d "$_d/$2" ] && return 0
    done
    return 1
}
_have_theme themes "$gtk_theme" || gtk_theme="TechOGR"
_have_theme icons "$gtk_icons" || gtk_icons="Papirus-Dark"
_have_theme icons "$gtk_icons" || gtk_icons="Adwaita"

# Sidebar bookmarks (Thunar / GTK file chooser). They need absolute paths,
# so they're written here for the current $HOME instead of shipped: the old
# repo copy pointed to /home/onelcrack/... and every entry failed to open.
[ -f "$HOME/.config/user-dirs.dirs" ] || xdg-user-dirs-update >/dev/null 2>&1
_bm="$HOME/.config/gtk-3.0/bookmarks"
if [ ! -f "$_bm" ] || grep "^file:///home/" "$_bm" | grep -qv "^file://$HOME/"; then
    mkdir -p "$HOME/.config/gtk-3.0"
    for _k in DOWNLOAD DOCUMENTS MUSIC VIDEOS PICTURES; do
        _p=$(xdg-user-dir "$_k" 2>/dev/null)
        [ -n "$_p" ] && [ "$_p" != "$HOME" ] && [ -d "$_p" ] &&
            python3 -c 'import sys, pathlib; print(pathlib.Path(sys.argv[1]).as_uri())' "$_p"
    done >"$_bm"
fi

# Set the gtk theme corresponding to rice
sed -i "$HOME"/.config/bspwm/config/xsettingsd \
    -e "s|Net/ThemeName .*|Net/ThemeName \"$gtk_theme\"|" \
    -e "s|Net/IconThemeName .*|Net/IconThemeName \"$gtk_icons\"|" \
    -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"$gtk_cursor\"|"

sed -i -e "s/Inherits=.*/Inherits=$gtk_cursor/" "$HOME"/.icons/default/index.theme

# Reload daemon and apply gtk theme
if pidof -q xsettingsd; then
    pkill -1 xsettingsd
fi
xsetroot -cursor_name left_ptr
unset _gtk_dir _d _bm _k _p
