# This file launch the bar/s
# bar.ini (look + modules) is generated by BarCtl from config/polybar.json
[ -f "${HOME}/.config/bspwm/rices/${RICE}/bar.ini" ] || "${HOME}"/.config/bspwm/bin/BarCtl render
for mon in $(polybar --list-monitors | cut -d":" -f1); do
	MONITOR=$mon polybar -q emi-bar -c "${HOME}"/.config/bspwm/rices/"${RICE}"/config.ini &
done
# Auto-hide daemon (exits by itself when auto-hide is off or already running)
"${HOME}"/.config/bspwm/bin/BarCtl daemon >/dev/null 2>&1 &
