# =============================================================
# Author:  TechOGR
# Repo:    https://github.com/TechOGR/bspwm_dotfiles_arch
#
# riceeq - a 10-band equalizer for EVERYTHING that plays (browser, Spotify,
# mpv, MPD...): a PipeWire filter-chain run as its own small process
# (`pipewire -c rice-eq.conf`, the user unit rice-eq.service). It is a
# WirePlumber "smart filter": inserted in front of the default output by
# itself, the default device stays the same, and stopping it puts the
# sound back as it was. Gains change live (pw-cli set-param), no restart.
#
# State: ~/.config/bspwm/config/eq.json  {"on": bool, "preset": str, "gains": [10 dB]}
#
# Copyright (C) 2021-2026 TechOGR <https://github.com/TechOGR>
# Licensed under GPL-3.0 license
# =============================================================

import json
import os
import subprocess

HOME = os.path.expanduser('~')
BSPWM = os.path.join(HOME, '.config/bspwm')
STATE = os.path.join(BSPWM, 'config/eq.json')
CONF = os.path.join(BSPWM, 'config/rice-eq.conf')
UNIT = 'rice-eq.service'
NODE = 'rice_eq_input'          # the filter's sink node (where the gains live)

FREQS = [31, 62, 125, 250, 500, 1000, 2000, 4000, 8000, 16000]
LABELS = ['31', '62', '125', '250', '500', '1K', '2K', '4K', '8K', '16K']
MAX_DB = 12.0

PRESETS = {
    'flat':       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'bass':       [7, 6, 4.5, 2, 0, 0, 0, 0, 0, 0],
    'bass_extra': [10, 8.5, 6, 3, 0.5, 0, 0, 0, 0.5, 1],
    'rock':       [5, 4, 2.5, 0, -1.5, -1, 1.5, 3, 4, 4.5],
    'pop':        [-1, 0.5, 2.5, 4, 4.5, 3, 1, 0, -0.5, -1],
    'electronic': [6, 5, 1.5, 0, -2, 1.5, 0.5, 2, 5, 5.5],
    'hiphop':     [6.5, 5.5, 2, 3, -1, -1, 1, -0.5, 1.5, 2.5],
    'vocal':      [-2, -1.5, -1, 1.5, 4, 4.5, 3.5, 1.5, 0, -1],
    'acoustic':   [3, 3, 2, 0.5, 1.5, 1.5, 3, 3.5, 3, 2],
    'treble':     [0, 0, 0, 0, 0, 0.5, 2.5, 5, 6.5, 7.5],
    'night':      [-3, -2, -1, 0, 1, 1.5, 1, -1, -3, -4.5],
}
PRESET_NAMES = {
    'flat': ('Flat', 'Plano'), 'bass': ('Bass', 'Graves'), 'bass_extra': ('Bass boost', 'Graves +'),
    'rock': ('Rock', 'Rock'), 'pop': ('Pop', 'Pop'), 'electronic': ('Electronic', 'Electrónica'),
    'hiphop': ('Hip-hop', 'Hip-hop'), 'vocal': ('Vocal', 'Voces'), 'acoustic': ('Acoustic', 'Acústica'),
    'treble': ('Treble', 'Agudos'), 'night': ('Night', 'Noche'), 'custom': ('Custom', 'Personal'),
}
ORDER = ['flat', 'bass', 'bass_extra', 'rock', 'pop', 'electronic', 'hiphop', 'vocal', 'acoustic', 'treble', 'night']


def load():
    try:
        st = json.load(open(STATE))
        gains = [max(-MAX_DB, min(MAX_DB, float(g))) for g in st.get('gains', [])][:10]
        if len(gains) == 10:
            return {'on': bool(st.get('on')), 'preset': st.get('preset', 'custom'), 'gains': gains}
    except (OSError, ValueError, TypeError):
        pass
    return {'on': False, 'preset': 'flat', 'gains': list(PRESETS['flat'])}


def save(st):
    os.makedirs(os.path.dirname(STATE), exist_ok=True)
    tmp = STATE + '.tmp'
    with open(tmp, 'w') as f:
        json.dump(st, f)
    os.replace(tmp, STATE)


def preamp(gains):
    """Lower the whole signal by the biggest boost: no clipping."""
    return -max(0.0, max(gains)) * 0.85


def _band(i, g):
    label = 'bq_lowshelf' if i == 0 else 'bq_highshelf' if i == 9 else 'bq_peaking'
    q = 0.7 if i in (0, 9) else 1.1
    return (f'{{ type = builtin name = eq{i} label = {label} '
            f'control = {{ "Freq" = {float(FREQS[i])} "Q" = {q} "Gain" = {float(g)} }} }}')


def write_conf(gains):
    """The filter graph with these gains (read when the process starts)."""
    pre = 10 ** (preamp(gains) / 20)
    nodes = '\n                    '.join([f'{{ type = builtin name = pre label = linear '
                                           f'control = {{ "Mult" = {pre:.4f} "Add" = 0.0 }} }}'] +
                                          [_band(i, g) for i, g in enumerate(gains)])
    links = '\n                    '.join(
        ['{ output = "pre:Out" input = "eq0:In" }'] +
        [f'{{ output = "eq{i}:Out" input = "eq{i + 1}:In" }}' for i in range(9)])
    text = f'''# Generated by ~/.config/bspwm/lib/riceeq.py (the music player's equalizer)
context.properties = {{ log.level = 0 }}
context.spa-libs = {{
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}}
context.modules = [
    {{ name = libpipewire-module-rt args = {{ nice.level = -11 }} flags = [ ifexists nofail ] }}
    {{ name = libpipewire-module-protocol-native }}
    {{ name = libpipewire-module-client-node }}
    {{ name = libpipewire-module-adapter }}
    {{ name = libpipewire-module-filter-chain
        args = {{
            node.description = "Rice Equalizer"
            media.name       = "Rice Equalizer"
            filter.graph = {{
                nodes = [
                    {nodes}
                ]
                links = [
                    {links}
                ]
            }}
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {{
                node.name = "{NODE}"
                media.class = Audio/Sink
                filter.smart = true
                filter.smart.name = "rice-eq"
            }}
            playback.props = {{
                node.name = "rice_eq_output"
                node.passive = true
                filter.smart = true
                filter.smart.name = "rice-eq"
            }}
        }}
    }}
]
'''
    os.makedirs(os.path.dirname(CONF), exist_ok=True)
    with open(CONF + '.tmp', 'w') as f:
        f.write(text)
    os.replace(CONF + '.tmp', CONF)


def _node_id():
    try:
        out = subprocess.run(['pw-dump'], capture_output=True, text=True, timeout=4).stdout
        for o in json.loads(out or '[]'):
            if o.get('type') == 'PipeWire:Interface:Node' and \
                    o.get('info', {}).get('props', {}).get('node.name') == NODE:
                return o['id']
    except (OSError, ValueError, subprocess.TimeoutExpired):
        pass
    return None


def running():
    return subprocess.run(['systemctl', '--user', 'is-active', '--quiet', UNIT]).returncode == 0


def set_gains(gains):
    """Live, on the running filter (True when it took them)."""
    nid = _node_id()
    if nid is None:
        return False
    parts = [f'"eq{i}:Gain" {float(g):.2f}' for i, g in enumerate(gains)]
    parts.append(f'"pre:Mult" {10 ** (preamp(gains) / 20):.4f}')
    r = subprocess.run(['pw-cli', 'set-param', str(nid), 'Props', '{ params = [ ' + ' '.join(parts) + ' ] }'],
                       capture_output=True, text=True, timeout=4)
    return r.returncode == 0


def apply(st):
    """Save the state and make the sound follow it: on/off and the gains."""
    save(st)
    write_conf(st['gains'])
    if st['on']:
        if running():
            set_gains(st['gains'])
        else:
            subprocess.run(['systemctl', '--user', 'enable', '--now', UNIT], capture_output=True)
    elif running():
        subprocess.run(['systemctl', '--user', 'disable', '--now', UNIT], capture_output=True)


def unit_text():
    return ('[Unit]\nDescription=Rice equalizer (PipeWire filter-chain, the music player)\n'
            'After=pipewire.service wireplumber.service\nBindsTo=pipewire.service\n\n'
            '[Service]\nExecStart=/usr/bin/pipewire -c %h/.config/bspwm/config/rice-eq.conf\n'
            'Restart=on-failure\nRestartSec=2\n\n[Install]\nWantedBy=pipewire.service\n')
